default['perl_modules'][:packages]  = %w[
  perl-core
  perl-Archive-Tar
  perl-Archive-Zip
  perl-Authen-SASL
  perl-Class-DBI-mysql
  perl-Crypt-DSA
  perl-Crypt-SSLeay
  perl-Digest-SHA1
  perl-Cache-Memcached
  perl-DBI
  perl-DBD-mysql
  perl-Digest-SHA
  perl-GD
  perl-HTML-Parser
  perl-IO-Compress-Zlib
  perl-IO-Socket-SSL
  perl-IPC-Run
  perl-Imager
  perl-Mail-Sendmail
  perl-Net-SSLeay
  perl-Net-SMTP-SSL
  perl-Net-SMTP-TLS
  perl-XML-Parser
  ImageMagick-perl
]